### PR TITLE
support implicit provider

### LINKED ISSUE #182: allow provider to be passed by the caller
```
The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.
│ Error: Module is incompatible with count, for_each, and depends_on
│ 
│   on modules/region-hub/main.tf line 16, in module "checkpoint":
│   16:     module.vpcs
│ 
│ The module at module.region_europe-west2.module.checkpoint.module.checkpointsw-cloudguardiaas
│ is a legacy module which contains its own local provider configurations, and so calls to it may
│ not use the count, for_each, or depends_on arguments.
│ 
│ If you also control the module
│ "git::https://github.com/CheckPointSW/CloudGuardIaaS.git?ref=72d58cf//terraform/gcp/high-availability",
│ consider updating this module to instead expect provider configurations to be passed by its
│ caller.
```

This is the piece that breaks the modern module support.

https://github.com/CheckPointSW/CloudGuardIaaS/blob/51702a157970a34496104d7cbc7e4d0e44f872e6/terraform/gcp/high-availability/main.tf#L1-L5

Should create a `versions.tf` instead, something like this: https://github.com/terraform-google-modules/terraform-google-network/blob/a93fd8ba6075dff58abdd3dbcb4487c29abc7168/modules/vpc/versions.tf#L17-L24

### PR DESCRIPTION
**Pull request by jetersen**
fixes #182

### CODE REVIEW

**Comment by jetersen** [comment]
Tested locally and it works the same but now allows implicit provider

**Comment by jetersen** [comment]
@gbrembati @chkp-romanka @chkp-natanelm @chkp-cgraffe would appreciate if you could take a look 😄

**Comment by jetersen** [comment]
@gbrembati @chkp-romanka @chkp-natanelm @chkp-cgraffe

after fixing the subnetwork_project I am able to apply this in terraform as well! 👏

**Comment by chkp-natanelm** [comment]
Hi @jetersen, 

Please see @chkp-dmitrygo reply at https://github.com/CheckPointSW/CloudGuardIaaS/issues/182.

Thanks

**Pull request closed without merging**
