### PR TITLE
Added lifecycle block to ignore ebs_block_device change to fix instan…

### PR DESCRIPTION
**Pull request by sankargopal-77**
Due to ebs_block_device details in  "aws_instance" resource, the instance is getting destroyed and recreated for every terraform apply.

To fix this issue, I've added below block in the code so that it accept the changes without recreating new EC2 instance.

lifecycle {
    ignore_changes = [ebs_block_device, ]
  }

### CODE REVIEW

**Comment by chkp-romanka** [comment]
Hi sankargopal-77
We are checking the issue and will update

**Comment by sankargopal-77** [comment]
Hi @chkp-romanka , Thanks for checking the PR. Could you please let me know when this change will be added into master?

**Comment by chkp-romanka** [comment]
Hi sankargopal-77
We delivered the fix you suggested as part of another pull request
Thank you for point out on this issue!

**Comment by chkp-romanka** [comment]
@sankargopal-77 
It is already in master :)

**Pull request closed without merging**
